use crate::common::d3d11_element::D3D11Element;
use crate::common::d3d11_gametype::D3D11GameType;
use crate::constants::gametype::{
    CategoryName, DxgiFormat, ElementName, ExtractSlot, ExtractTechnique,
};

pub struct HOKGameType;

impl HOKGameType {
    pub fn initialize() -> Vec<D3D11GameType> {
        vec![
            D3D11GameType::from_parts(
                "CPU_P12_",
                vec![D3D11Element::new(
                    ElementName::POSITION,
                    DxgiFormat::R32G32B32_FLOAT,
                    ExtractSlot::VB0,
                    ExtractTechnique::TRIANGLELIST,
                    CategoryName::POSITION,
                    CategoryName::POSITION,
                    "12",
                )],
            ),
            D3D11GameType::from_parts(
                "CPU_P12_N12_",
                vec![
                    D3D11Element::new(
                        ElementName::POSITION,
                        DxgiFormat::R32G32B32_FLOAT,
                        ExtractSlot::VB0,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::POSITION,
                        CategoryName::POSITION,
                        "12",
                    ),
                    D3D11Element::new(
                        ElementName::NORMAL,
                        DxgiFormat::R32G32B32_FLOAT,
                        ExtractSlot::VB1,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::NORMAL,
                        CategoryName::NORMAL,
                        "12",
                    ),
                ],
            ),
            D3D11GameType::from_parts(
                "CPU_P12_N12_TA16_T8_T1-8_T2-8_",
                vec![
                    D3D11Element::new(
                        ElementName::POSITION,
                        DxgiFormat::R32G32B32_FLOAT,
                        ExtractSlot::VB0,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::POSITION,
                        CategoryName::POSITION,
                        "12",
                    ),
                    D3D11Element::new(
                        ElementName::NORMAL,
                        DxgiFormat::R32G32B32_FLOAT,
                        ExtractSlot::VB1,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::NORMAL,
                        CategoryName::NORMAL,
                        "12",
                    ),
                    D3D11Element::new(
                        ElementName::TANGENT,
                        DxgiFormat::R32G32B32A32_FLOAT,
                        ExtractSlot::VB2,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::TANGENT,
                        CategoryName::TANGENT,
                        "16",
                    ),
                    D3D11Element::new(
                        ElementName::TEXCOORD,
                        DxgiFormat::R32G32_FLOAT,
                        ExtractSlot::VB3,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::TEXCOORD,
                        CategoryName::TEXCOORD,
                        "8",
                    ),
                    D3D11Element::new(
                        ElementName::TEXCOORD,
                        DxgiFormat::R32G32_FLOAT,
                        ExtractSlot::VB3,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::TEXCOORD,
                        CategoryName::TEXCOORD,
                        "8",
                    ),
                    D3D11Element::new(
                        ElementName::TEXCOORD,
                        DxgiFormat::R32G32_FLOAT,
                        ExtractSlot::VB3,
                        ExtractTechnique::TRIANGLELIST,
                        CategoryName::TEXCOORD,
                        CategoryName::TEXCOORD,
                        "8",
                    ),
                ],
            ),
        ]
    }
}
